server:
  port: 8083

spring:
  application:
    name: enrollment-service
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb+srv://linux:redhat@alphappdb.whupgqn.mongodb.net/cb_auth?retryWrites=true&w=majority&appName=cdec-dev}

jwt:
  secret: ${JWT_SECRET}

logging:
  level:
    in.cloudblitz.enrollment: DEBUG
